FROM ubuntu
MAINTAINER hvv19890828 <hvv19890828@gmail.com>
RUN apt-get update -y  && \
    apt-get upgrade -y && \
    apt-get install -y net-tools
# && \
#    apt-get install -y git && \
#    git clone https://github.com/benzea/gnome-network-displays.git && \
#    chmod -R 777 gnome-network-displays && \
#    cd gnome-network-displays && \
#    apt-get install -y python3-pip && \
#    pip3 install meson && \
#    meson build && \
#    chmod -R 777 build && \
#    cd build  && \
#    meson install
#EXPOSE 
CMD ["sleep", "5000"]
