---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smbcreds
  namespace: default
spec:
  encryptedData:
    password: AgATF2xxd6tvyoXCl5fKtUGziCxeqU/pfiCel8vG1cgrBIghbRUBv97T/SAwxGKx0LgzVCjlwZBE6mtHd6/08VCEPVdqDBKkj8qsd5uT9y6CzNaS0oa0sg74o/tAkWDHLFZ0k4chgqDKlle86AuUMjiuJzDLIDJTBo3k3sD7U31r9NTpKn9zveoPKRium7u1YAV7m0fLnkaAYY7rjbXl4goRGFT5zgsHmwYS2eK7EvnNOx5q2WpKYRG/5KO1D2Lb8laubNwbTgS2fSTESX9n9QCLJqA65ChQt18wyBrg32jKzt7Czv0U9lU73JRbhlbxhOfbQKRoEItWVVRSMjSnaHii3tiw+TWTsoyzEcNZz9FuLPKXTQ9hrdoiNZyAlE6obxieGyEdKT73Uo6Ike/rG4fivZE1qoXl3GfSQbv6c2WJgZDBQQG6xHmKKov1PeOslqm+9DVW07ledT1Z4NavjKlbX6pEJW9e8WBDLpYvAacPfMDexzdZI0Qquz/LzIqwWcV7wQ0275kgNUnuvkMDET7urO8aisSSporoJKIUnrnO7GOl4HdHJpousMYaiKjfZJmIIdSj8Owz8r+OVdSMSGVO9DCNpcf8qQ0qVEfjryprm8JKuAEa9ddUjAC+M+rPSF/mR5mt6TLCrqTTcGqgV2hfCVQOF6arFNCB9h2ZdounmSYZXkuxcwpIgwS7gaU2g/bNC1LZNgwTPkfqpQ==
    username: AgB+iYWPQrhgADwKBDxd2mRSdmmA09SMHdKhX40I95K6M4ZdMD86SQoLXSofjxfwBRgKR2b6S1EzEtA9fO9/XvxVG/wgt8X2GMrShlT4PUcFkTVVHMFiR/e4oTkboqQyzwvjL1o5W473UY9q4THeUH5HnAlS0xTJ8UCkkroWmY2bIX2/1aL7qUMGo21dqYoENCDG2D8RXaGEaOGar6YKIzHPRsp6ZBUzbhAau7u+G6KheubhDKQA7jpMyIVQkyraWq9BfOsixBw6WW53jCeC+XHcE6TW0lnwnPsW+Rbvam9ZB14gHbCV7UzbETrq6YXum+1gMUmRP0+UM+FZdXfOP+WV//df+CKIi0mPXuNAIBWS8+Qml6BYgKnUJ1kU6+QeqlTtlMUMTfI1DYZipk2WU32wTGbA/lUVKu4K12eeishjEIHod2nUAU4ixIgbhfdiYnlB9VbAollTOe44mm95bOKyy9VBk7Cmmv+OFJDFVfWZrP8KtVdUJs2cLS3rDPdbpzkkBNEtVdiWS6+rD/BXwozGAOBlMboc47nkZzq2ZAHLDofhJOWd3XcarkgYxlFc+uWRHarAV9ycvbiQWfrXckhoTtXWi3xricohZ7pEFEFeHHHvRHNf8lpUmDw03U5iG5U7rmJAP14HSjJfrMzGuVvPxYGn5kGk6LgASRpnnd0yA80wDqUV7lWHTQ92+DlUv4+NGuL3rG0HQh9yunyWn53SEYWoUjI=
  template:
    metadata:
      name: smbcreds
      namespace: default
    type: Opaque