---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smbcreds
  namespace: kube-system
spec:
  encryptedData:
    password: AgC/AA/PxIFbBSpFCFp8rqy3eI+HYWVuOvKeiAs+y08xHI6mqy52sy2zX1KvCFYSqk29Xb9vYkGgLQUYxG4KwVpovhUd+2ZMrx4mdztHgkNf9MECN9hKrNSttvAlg8jUIt1+qyyX9M/WuWmVToTPhJmC60xPZKfgMN1xCkStRleGgm82yY7W33JD4U1A5/zySCErn8WHFLUybh1orY4U2Xj+emOxV+7BNLVRj0ww+Wor19IrvQwyZ0zvBaWc+DHx+O5Fzq4W3ppp7LNRS6ahxuGnpkZAzpS/0l/dsJAQEcwRCuh7Bw2gZ2gKoFciPLldh6IDOFV2CZbAzn2aXt92NoYTp2YIU4fz+ZvfJnzbUzC3KeV08RQd6ojA/2vnszcz6z+99qlr55id+MoWK/EaEwifneKVX/xP5OixPzTjyBSmVFLmSBzsAVOeMm2+fxf9cTiFS49VCsK/UVm/HaTdlHxKvU6jDCfM6kNQvEO2EamXO+KGuNdlPdmADO5EhL6PaaFIHQWjUoDkxdj2ngFiKXDBEd04a4z6dbAZ9a2oyMI6bMwAQJBvp5alX7aOQGplp37rt5pLWYN0T4bELqyWLpeyKzqTuaW5UMsIcsS6qXx05ez+sCRRSHPM5M1HxIkNVv7h/OdnWsvDt3aSd96GBxAYpz6u+8BhzJzsVlpbS4yjECZC6dbJHPX8zRybnS+lAdFA1oicow4BWV94
    username: AgBEf/d+r01iAFID66bpMoVac3ZsCnqqQN9MbdSUYBLRS6g7nVQRnPPTeLI/8xrojPL8aREuh8aasr3F9URCqrjV/NQ7hWhKkkIlVvCg3nbHnVjjA04CCt64YCc4tt2wiWUVovQohnXvthbTter4CnpzjGMNH7ILUU8kQHThJOQuYNGF76mVQ2HApLPyWU0solCaKjmnEJenRjZuSpEleLr5btDdexRVZC5E4DUAf5pFzpS67DQpUfG/oMIlkwwFQjPMd11e5TlXYcsLidWxXlDIUqv27QiiFaAbkUF2BoXEJCeYBySBCJcg4OL12Tgjflypj37tvIg97LQW1t20FqE8k5rsp9JnAhkqbHCFKQk4Kxe/qHyBOn1nBp7BKrtLXSGylAAzuBOYwVg3TDEZzsRzK1RV4aJ7AfQpL2CxE3xVV3rpF7djrRxYJ6oFX8V0m/GY4LuagShHJveFNJGKpywpuEpwuaEjLz+7PGctvXa3JSAzDS4D/uraTfPFX3H6bbszGyPCOfvCKMde4EwJc3zy2O7Qgsjk9dmym6uIZtwL/OTMIQpEZI1fbLWPqI5kF2g9TBqAmNNMA/PBK5fgamEFES2lTRqbj5xjcbmVd+RQmOs9EN4LipCrP3uF8iSwVbWhCsz+UyNGO7VKzRcLlrRoGOlc7e+06rQeaoEobXopGSrAwBuR77NMofBp6DklKGvuiBEkxhM=
  template:
    metadata:
      name: smbcreds
      namespace: kube-system
    type: Opaque