---
version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /scripts_hvv/sys_routines/deluge/config:/config
      - /home/hvv/Downloads/tmp/tor:/downloads
    restart: unless-stopped
