apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniocreds
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCxWhYwlZsBa8LKEUUfFn4emafnfgXopYKFMrBZz0Zy7ryEnmfLYdXFYw7H8SBg6h/6PhjVpgxLk2JqBi4kMn4fsIAUpq2D4wDQQMiHf3A55kDsXVjKARSazT7598S2ZHnXOdPtGzEQNgh4RfIYhPB91skg3sK3zUGh8IU9nDbMoAKKUiL/6onY82+xpW/+mjyc35rxPeCAt2Fro3OlF8dcJg8xAlcjcAAzqzDZVkoxuvh2eCAhuYE+NbU4RNbe8B80OimJl/6hsTcC76VOgOcCAoFjsUf1y44NH0iyFtpIGqkxI2BXPn4wKZdshhkkloY/yxpdHB+da5PSOAro2HDkPUiu04rKr6uhzvqEaHJi3MnDKQp+rZjG1V/BuXUTJkezxiSI30oYshpJYndX+iG3KokOCvASNwZMq1L7x2aR22tXPL9ZLr8dGz8g0bZYpbBteIHjLuEIKwRR7vpRtdlPHrtWjgu4rTQEkugfX4XMlEMdrZ120URXuvtM1gWp+fMb2vl2+FHCVcs3FWQFXbZQS3SyACbiCjzj4Rmm1j8OxphBf2m/idLHIPy7LLSDT8bA1rrnZbLQLTrup2QxNUpDKz2nnk5NHnpDVACi3OVaFYYgLYrU9QjYYCx0VQXMIsb6EKfqGSnzvk8WRzp+4Do691Ux/KY7LPIxo/5KMHq/niUsAVUBfk1thaxCLawWHa6fKnN1WImYAoaC
    rootUser: AgDqmX5Eykv7EhgD+jglwd9UM9XjXp6/KPqLEeIc+1rWFmqMloyzFUy3ebZGQhVfOYWLgAQKolJr9wkhyDBDSOmSETn744XiVrl5KJFzfXq68IpE0b2tUTSx0q/8CBOsDOUagSwEC8jCBH86uxzVyWbRPLClfCckVpPnQemonlhRE2SzrngVstcIr/QlqUrIdy8o4sRPKdlEigs1jz3AYMEU1YZno8t7p1KmPnBJYR0Le1/+CaVVu6ltBmNyGSD5HI81uVtA8G+wrRVWnHNOzwjxtoPNW4Y48LKNEY+5T+/bwY4lt/yQWmKdVHFOpg7CEgGsAeHMB2IEAfluFoDfsrPuoELKVXTD6r1hbaMoQoHVTBe2yedIwtS07qXP6s+fat4q/m7hnpLCiLZ45Sn+QiKUW6tr1jdqRp4U6YFC0npUbHZrcvBXH0h6UDS+jNpEZZbmGTQ69HNioE7fkvlSRLHedmoESTDLFIgUgarP/F+ZxA/j/mC/G+DtGwyldmfDiFRQqnNMORSCbUVLPV0YipHINxnj9Dp6136PDhDH1tEYrr+HaMcLfipd4RFV2dTI5Yxtnl4UsvKgPPnICNTDDFO6EeyDCDqjVctR4HSHW4TgHZQfCs8UuQXFecqiJcFQCR8Nz4PJhTuWnDxqyXKbKgZpUzLRtXlznjGPz7QL2uidrojwauiOHuc6Bj9Rq3KVYoEC/cbKW6yDo3LlRQ==
  template:
    metadata:
      name: miniocreds
      namespace: minio
    type: Opaque
