---
- name : test playbook
  hosts : tvm1
  become: yes
  
  vars :
    src1 : ./playbook1.yml
    dst : / 
  
  tasks:
  - name: Get ifconfig on master
    shell: echo "2312553484874832join98374590347593487598034  98(*_(&*hjgjlhvgljhsg\flsjfgflhdfskjhkjsdh --- jhkjhk98374590347593487598034  98(*_(&*hjgjlhvgljhsg\flsjfgflhdfskjhkjsdh --- jhkjhkjhkjhkjhjsisy48"
    register: MIFReg
  - name: Get 
    set_fact:
      MIFRes: "{{ MIFReg.stdout | regex_search(MIFRGXP) }}"
    vars:
      MIFRGXP: 'join.*'
  - debug:
      var: MIFRes
