---
- name : test playbook
  hosts : tvm
  become: yes
  
  vars :
    src1 : ./playbook1.yml
    dst : / 
  
  tasks:
  - name: var to be parsed
    shell: ifconfig | grep -A1 enp0s8 | grep inet
    register: ifReg
  - name: set regex
    set_fact:
      re: '--yyy\s+(?P<digit>\d+\.\d+\.\d+-\d+)'
  - set_fact:
      ifRes: "{{ ifReg.stdout | regex_search(re, '\\g<digit>') }}" 
  - debug:
      var: value
