# @enabled on
# @normal_password 77A627eF08c
# @admin_username admin
# @admin_password ac4219cf316adfa633254254b96e3c979ca375eb
# @normal_username hvv19890828


webcontrol_interface 1
webcontrol_port 7999
camera camera-1.conf
setup_mode off
webcontrol_parms 2
webcontrol_localhost on
