# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:
NODES = 3
NODES_START = 1
BRIF = "wlp2s0"
XRAM = 2048
XCPU = 2
IP_NW = "192.168.5."
#"enx000ec79ecb52""wlp2s0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  (NODES_START..NODES).each do |i|
      config.vm.define "host#{i}" do |host|
        host.vm.provider "virtualbox" do |vb|
            vb.name = "host#{i}"
            vb.memory = XRAM
            vb.cpus = XCPU
        end
        host.vm.hostname = "host#{i}"
        host.vm.network :private_network, ip: IP_NW + "#{10 + i}"
        host.vm.network "forwarded_port", guest: 22, host: "#{54320 + i}",
#        host.vm.network "public_network", :ip => IP_NW + "#{210 + i}", :netmask => '255.255.255.0', :bridge => BRIF,
          auto_correct: true
#        host.vm.provision "shell",
#                run: "always",
#                inline: "route add default gw 192.168.0.1"
        host.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        host.vm.provision "ssh-setup", type: "shell", :path => "ubuntu/ssh-setup.sh"
      end
  end
end
