# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:
NODES = 2
NODES_START = 1
BRIF = "wlp2s0"
XRAM = 2048
XCPU = 2
IP_NW = "192.168.6."
#"enx000ec79ecb52""wlp2s0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
#  config.disksize.size = '30GB'
  config.vm.box_check_update = true
#  config.vm.base_mac = nil
  (NODES_START..NODES).each do |i|
      config.vm.define "host#{i}" do |host|
        host.vm.provider "virtualbox" do |vb|
            vb.name = "host#{i}"
            vb.memory = XRAM
            vb.cpus = XCPU
        end
        host.vm.hostname = "host#{i}"
        host.vm.network :private_network, ip: IP_NW + "#{30 + i}", auto_correct: true
#, virtualbox__intnet: true
        host.vm.network "forwarded_port", guest: 22, host: "#{54320 + i}", auto_correct: true
#Bridge Adapter Setup
#        host.vm.network "public_network", :ip => IP_NW + "#{210 + i}", :netmask => '255.255.255.0', :bridge => BRIF,
#        host.vm.provision "shell",
#                run: "always",
#                inline: "route add default gw 192.168.0.1"
#Bridge Adapter Setup
#Custom Port Forwarding
#        if "host#{i}" == "host1"
#           host.vm.network "forwarded_port", guest:54003, host:54003, auto_correct: true
#        end 
#Custom Port Forwarding
        host.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        host.vm.provision "ssh-setup", type: "shell", :path => "ubuntu/common-setup.sh"
      end
  end
end

